apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: b4tman/squid:5.6
        env:
          - name: SQUID_CONFIG_FILE
            value: /etc/squid/squid.conf
        ports:
        - containerPort: 3128
