apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  labels:
    app: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
        image: b4tman/squid:5.6
        volumeMounts:
          - name: squid-config
            mountPath: /etc/squid/mysquid.conf
            subPath: mysquid.conf
        env:
          - name: SQUID_CONFIG_FILE
            value: /etc/squid/mysquid.conf
        ports:
        - containerPort: 3128
      volumes:
        - name: squid-config
          configMap:
            name: mysquid.conf
