apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid-deployment
  labels:
    app: squid
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      containers:
      - name: squid
#        image: b4tman/squid:5.6
        image: fredouye/my-squid:0.1-alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: squid-config
            mountPath: /etc/squid/mysquid.conf
            subPath: mysquid.conf
            readOnly: true
          - name: squid-cache
            mountPath: /var/cache/squid
        env:
          - name: SQUID_CONFIG_FILE
            value: /etc/squid/mysquid.conf
          - name: TZ
            value: Europe/Paris
        ports:
        - containerPort: 3128
          name: squid
      securityContext:
        fsGroup: 31
      readinessProbe:
          initialDelaySeconds: 1
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 1
          tcpSocket:
            host:
            port: 3128
      volumes:
        - name: squid-config
          configMap:
            name: mysquid.conf
        - name: squid-cache
          persistentVolumeClaim:
            claimName: squid-cache
