apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: proxy

resources:
- configmap.yml
- deployment.yml
- pvc.yml
- service.yml

commonAnnotations:
  conf/version: 03.08.2022-16h39
