apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: squid

resources:
- configmap.yml
- deployment.yml
- pvc.yml
- service.yml

commonAnnotations:
  conf/version: 04.08.2022-15h40
