apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: squid-cache
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi
