apiVersion: v1
kind: Service
metadata:
  name: squid
spec:
  type: LoadBalancer
  selector:
    app: squid
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 3128
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.3.201
