apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  type: LoadBalancer
  selector:
    app: smtp
ports:
  - name: smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: smtps
    port: 587
    protocol: TCP
    targetPort: 587
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.3.202
