apiVersion: v1
kind: Service
metadata:
  name: smtp
spec:
  type: LoadBalancer
  selector:
    app: smtp
  ports:
    - name: smtp
      port: 25
      protocol: TCP
      targetPort: 25
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerIP: 192.168.3.202
